export { default as assert } from './assert';
export * as async_hooks from './async_hooks';
export * as buffer from './buffer';
export * as child_process from './child_process';
export { default as console } from './console';
export * as crypto from './crypto';
export * as dgram from './dgram';
export * as diagnostics_channel from './diagnostics_channel';
export * as dns from './dns';
export { default as events } from './events';
export * as fs from './fs';
export * as http from './http';
export * as http2 from './http2';
export * as https from './https';
export { default as module } from './module';
export * as net from './net';
export * as os from './os';
export { default as path } from './path';
export * as perf_hooks from './perf_hooks';
export { default as process } from './process';
export * as punycode from './punycode';
export * as querystring from './querystring';
export * as readline from './readline';
export { default as stream } from './stream';
export * as string_decoder from './string_decoder';
export * as timers from './timers';
export * as tls from './tls';
export * as tty from './tty';
export * as url from './url';
export * as util from './util';
export * as vm from './vm';
export * as worker_threads from './worker_threads';
export * as zlib from './zlib';
